# Application name
spring.application.name=animalshelter

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/animal_shelter
spring.datasource.username=postgres
spring.datasource.password=Jerry_1330329

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Disable Open Session in View
spring.jpa.open-in-view=false

# App port
server.port=8080

